/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/IkhhgiBumOs
 */
import { Button } from "@/components/ui/button"

export function HomeAtlantic() {
  return (
    <div className="bg-black text-white">
      <section className="max-w-6xl mx-auto px-4 py-20 text-center">
        <div className="mb-12">
          <h1 className="text-6xl font-bold mb-4">We turn your ideas into software powered by AI</h1>
          <p className="text-xl">
            LIKA is a software development company that provides software solutions for everyone, everywhere,
            integrating AI into your projects.
          </p>
        </div>
        <div className="space-x-4">
          <Button className="bg-purple-600 text-white">
            Book a meeting <ExternalLinkIcon className="ml-2" />
          </Button>
          <Button className="bg-transparent border border-gray-200 text-white dark:border-gray-800">
            Successful cases <StarIcon className="ml-2" />
          </Button>
        </div>
      </section>
      <section className="py-20">
        <div className="max-w-6xl mx-auto px-4">
          <h2 className="text-center text-2xl mb-8">OUR PARTNERS</h2>
          <div className="flex justify-center items-center space-x-12">
            <img
              alt="Skrapy logo"
              className="h-10"
              height="40"
              src="/placeholder.svg"
              style={{
                aspectRatio: "120/40",
                objectFit: "cover",
              }}
              width="120"
            />
            <img
              alt="Bariloche Rent a Boat logo"
              className="h-10"
              height="40"
              src="/placeholder.svg"
              style={{
                aspectRatio: "120/40",
                objectFit: "cover",
              }}
              width="120"
            />
            <img
              alt="FITNESS UY logo"
              className="h-10"
              height="40"
              src="/placeholder.svg"
              style={{
                aspectRatio: "120/40",
                objectFit: "cover",
              }}
              width="120"
            />
            <img
              alt="Tapy logo"
              className="h-10"
              height="40"
              src="/placeholder.svg"
              style={{
                aspectRatio: "120/40",
                objectFit: "cover",
              }}
              width="120"
            />
            <img
              alt="PayDrink logo"
              className="h-10"
              height="40"
              src="/placeholder.svg"
              style={{
                aspectRatio: "120/40",
                objectFit: "cover",
              }}
              width="120"
            />
            <img
              alt="Skrapy logo"
              className="h-10"
              height="40"
              src="/placeholder.svg"
              style={{
                aspectRatio: "120/40",
                objectFit: "cover",
              }}
              width="120"
            />
            <img
              alt="Bariloche Rent a Boat logo"
              className="h-10"
              height="40"
              src="/placeholder.svg"
              style={{
                aspectRatio: "120/40",
                objectFit: "cover",
              }}
              width="120"
            />
            <img
              alt="FITNESS UY logo"
              className="h-10"
              height="40"
              src="/placeholder.svg"
              style={{
                aspectRatio: "120/40",
                objectFit: "cover",
              }}
              width="120"
            />
          </div>
          <p className="text-center text-xl mt-12">Trusted by +100 companies around the world</p>
        </div>
      </section>
    </div>
  )
}


function ExternalLinkIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />
      <polyline points="15 3 21 3 21 9" />
      <line x1="10" x2="21" y1="14" y2="3" />
    </svg>
  )
}


function StarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}
